version: "3.3"

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3         # enable S3 only
      - DEBUG=1
    ports:
      - "4566:4566"         # Localstack main endpoint
